import { buildJsonSchemas } from "fastify-zod";
import {
	tagSchema,
	loginSchema,
	puzzleEntitySchema,
	reportSchema,
	userDtoSchema,
	puzzleMetricsSchema,
	validatorEntitySchema,
	registerSchema,
	difficultySchema,
	identifierSchema,
	userEntitySchema,
	puzzleVisibilitySchema,
	submissionEntitySchema,
	loginResponseSchema,
	registerResponseSchema,
	tokenSchema,
	messageSchema,
	authenticatedInfoSchema,
	paginatedQuerySchema,
	paginatedQueryResponseSchema,
	pistonFileSchema,
	pistonExecuteRequestSchema,
	pistonExecuteResponseSchema,
	puzzleResultSchema,
	editPuzzleSchema,
	acceptedDateSchema,
	createPuzzleSchema,
	pistonExecuteResponseErrorSchema,
	pistonExecuteResponseSuccessSchema
} from "types";

export const { schemas, $ref } = buildJsonSchemas({
	tagSchema,
	loginSchema,
	puzzleEntitySchema,
	reportSchema,
	userDtoSchema,
	puzzleMetricsSchema,
	validatorEntitySchema,
	registerSchema,
	difficultySchema,
	identifierSchema,
	userEntitySchema,
	visibilitySchema: puzzleVisibilitySchema,
	submissionEntitySchema,
	loginResponseSchema,
	registerResponseSchema,
	tokenSchema,
	messageSchema,
	authenticatedInfoSchema,
	paginatedQuerySchema,
	paginatedQueryResponseSchema,
	pistonFileSchema,
	pistonExecuteRequestSchema,
	pistonExecuteResponseSchema,
	puzzleResultSchema,
	editPuzzleSchema,
	acceptedDateSchema,
	createPuzzleSchema,
	pistonExecuteResponseErrorSchema,
	pistonExecuteResponseSuccessSchema
});
