export const permissionEnum = {
	SOLVE_PUZZLES: "SOLVE_PUZZLES",
	CREATE_PUZZLES: "CREATE_PUZZLES",
	EDIT_PUZZLES: "EDIT_PUZZLES",
	DELETE_PUZZLES: "DELETE_PUZZLES",
	MANAGE_USERS: "MANAGE_USERS",
	MANAGE_CONTENT: "MANAGE_CONTENT"
};
