export const DEFAULT_GAME_LENGTH_IN_MINUTES = 15;
export const DEFAULT_GAME_LENGTH_IN_SECONDS = DEFAULT_GAME_LENGTH_IN_MINUTES * 60;
export const DEFAULT_GAME_LENGTH_IN_MILLISECONDS = DEFAULT_GAME_LENGTH_IN_SECONDS * 1000;

export const MINIMUM_PLAYERS_IN_GAME = 1;
