defmodule CodincodApi.Typegen do
  @moduledoc """
  Utilities for generating TypeScript definitions that mirror the backend's
  validation rules and response payloads.

  This generator focuses on the portions of the API that already exist in the
  Phoenix migration (authentication and account preferences). As more routes are
  migrated the generator can be extended with additional sections.
  """

  alias CodincodApi.Accounts.{Preference, User}

  @default_destination Path.expand(
                         Path.join([
                           __DIR__,
                           "..",
                           "..",
                           "..",
                           "..",
                           "types",
                           "src",
                           "elixir-generated.ts"
                         ])
                       )

  @doc "Returns the default output path for the generated TypeScript file."
  @spec default_destination() :: String.t()
  def default_destination, do: @default_destination

  @doc "Generates the TypeScript file using the provided options."
  @spec generate(keyword()) :: {:ok, String.t()} | {:error, term()}
  def generate(opts \\ []) do
    dest =
      opts
      |> Keyword.get(:dest, default_destination())
      |> Path.expand(File.cwd!())

    data = %{
      auth: auth_config(),
      preferences: preferences_config(),
      generated_at: DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.to_iso8601()
    }

    content = render_typescript(data)

    with :ok <- File.mkdir_p(Path.dirname(dest)),
         :ok <- File.write(dest, content) do
      {:ok, dest}
    end
  end

  defp auth_config do
    %{
      username: %{
        min_length: User.username_min_length(),
        max_length: User.username_max_length(),
        regex: User.username_regex()
      },
      password: %{
        min_length: User.password_min_length()
      },
      email: %{
        regex: User.email_regex()
      }
    }
  end

  defp preferences_config do
    %{
      theme_options: Preference.theme_options()
    }
  end

  defp render_typescript(%{auth: auth, preferences: prefs, generated_at: generated_at}) do
    username_regex = regex_literal(auth.username.regex)
    email_regex = regex_literal(auth.email.regex)
    theme_options = format_array(prefs.theme_options)

    [
      "/* eslint-disable */",
      "// Auto-generated by `mix codincod.gen_types`. Do not edit manually.",
      "// Last generated: #{generated_at}",
      "",
      "export const AUTH_VALIDATION = {",
      "  username: {",
      "    minLength: #{auth.username.min_length},",
      "    maxLength: #{auth.username.max_length},",
      "    allowedCharacters: #{username_regex},",
      "  },",
      "  email: {",
      "    pattern: #{email_regex},",
      "  },",
      "  password: {",
      "    minLength: #{auth.password.min_length},",
      "  },",
      "} as const;",
      "",
      "export const ACCOUNT_PREFERENCES = {",
      "  themeOptions: #{theme_options},",
      "} as const;",
      "",
      "export type AccountPreferencesPayload = {",
      "  preferredLanguage: string | null;",
      "  theme: (typeof ACCOUNT_PREFERENCES.themeOptions)[number] | null;",
      "  blockedUsers: string[];",
      "  editor: Record<string, unknown>;",
      "};",
      "",
      "export type AccountPreferencesResponse = AccountPreferencesPayload;",
      ""
    ]
    |> Enum.join("\n")
  end

  defp regex_literal(%Regex{} = regex) do
    source = Regex.source(regex) |> String.replace("/", "\\/")
    opts = Regex.opts(regex)

    if opts == "" do
      "/#{source}/"
    else
      "/#{source}/#{opts}"
    end
  end

  defp format_array([]), do: "[]"

  defp format_array(list) when is_list(list) do
    values =
      list
      |> Enum.map(&inspect/1)
      |> Enum.join(", ")

    "[#{values}]"
  end
end
