/* eslint-disable */
// Auto-generated by `mix codincod.gen_types`. Do not edit manually.
// Last generated: 2025-11-02T00:00:40Z

export const AUTH_VALIDATION = {
	username: {
		minLength: 3,
		maxLength: 20,
		allowedCharacters: /^[A-Za-z0-9_-]+$/,
	},
	email: {
		pattern: /^[^\s@]+@[^\s@]+$/,
	},
	password: {
		minLength: 14,
	},
} as const;

export const ACCOUNT_PREFERENCES = {
	themeOptions: ["dark", "light"],
} as const;

export type AccountPreferencesPayload = {
	preferredLanguage: string | null;
	theme: (typeof ACCOUNT_PREFERENCES.themeOptions)[number] | null;
	blockedUsers: string[];
	editor: Record<string, unknown>;
};

export type AccountPreferencesResponse = AccountPreferencesPayload;
