import mongoose from "mongoose";
import { PUZZLE, VALIDATOR } from "../../utils/constants/model.js";

/**
 * IDEA: Eventually add validator types
 * there could be different validators, hidden generated by the system, and public testcases
 * this could mitigate users that just look at the public test cases and thus help catch code that technically is wrong, but passes the visible validators (to all users).
 */
const validatorSchema = new mongoose.Schema({
	createdAt: {
		default: Date.now,
		type: Date
	},
	input: {
		required: true,
		type: String
	},
	output: {
		required: true,
		type: String
	},
	puzzleId: {
		ref: PUZZLE,
		required: true, // Ensure every validator belongs to a puzzle
		type: mongoose.Schema.Types.ObjectId
	},
	updatedAt: {
		default: Date.now,
		type: Date
	}
});

const Validator = mongoose.model(VALIDATOR, validatorSchema);
export default Validator;
