import { Schema } from "mongoose";
import { GameOptions } from "types";
import languageSchema from "../programming-language/language.js";

/**
 * IDEA: Eventually add gameOptions types
 * there could be different gameOptions, hidden generated by the system, and public test-cases
 * this could mitigate users that just look at the public test cases and thus help catch code that technically is wrong, but passes the visible gameOptionss (to all users).
 */
const gameOptionsSchema = new Schema<GameOptions>({
	allowedLanguages: [languageSchema],
	maxGameDurationInSeconds: {
		required: true,
		type: Number
	},
	mode: {
		required: true,
		type: String
	},
	visibility: {
		required: true,
		type: String
	}
});

export default gameOptionsSchema;
