defmodule CodincodApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :codincod_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_codincod_api_key",
    signing_salt: "lOUmvnf8",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # WebSocket endpoint for real-time features (games, notifications, etc.)
  socket "/socket", CodincodApiWeb.UserSocket,
    websocket: [
      connect_info: [:peer_data, :x_headers, :uri]
      # check_origin is handled at endpoint level in dev.exs (false) and can be configured in prod
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :codincod_api,
    gzip: not code_reloading?,
    only: CodincodApiWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :codincod_api
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

   plug CORSPlug,
    origin: [
      ~r/^https?:\/\/localhost:5173$/,
      ~r/^https?:\/\/localhost:3000$/,  # Common React dev port
      ~r/^https?:\/\/(www\.)?codincod\.com$/,
    ],
    credentials: true,  # CRITICAL for cookies!
    max_age: 86400,
    headers: ["Authorization", "Content-Type", "Accept", "Origin"],
    expose: ["Set-Cookie"]  # Explicitly expose Set-Cookie header

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CodincodApiWeb.Router
end
