import { Schema } from "mongoose";
import { PuzzleLanguage, PuzzleLanguageVersion } from "types";
/**
 * IDEA: Eventually add gameOptions types
 * there could be different gameOptions, hidden generated by the system, and public test-cases
 * this could mitigate users that just look at the public test cases and thus help catch code that technically is wrong, but passes the visible gameOptionss (to all users).
 */
const languageSchema = new Schema<{
	language: PuzzleLanguage;
	version: PuzzleLanguageVersion;
}>({
	language: {
		required: true,
		type: String
	},
	version: {
		required: true,
		type: String
	}
});

export default languageSchema;
