name: Format

on: push

concurrency:
  group: ci-${{ github.ref }}-formatting
  cancel-in-progress: true

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install packages
        run: pnpm i

      - name: Format code
        run: pnpm format

      - uses: stefanzweifel/git-auto-commit-action@v5
