name: Sync Repo-Specific READMEs

on:
  push:
    paths:
      - 'frontend/README.md'
      - 'backend/README.md'
      - 'types/README.md'
      - 'README.md'

jobs:
  sync-readmes:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - name: frontend
            path: frontend/README.md
            target_repo: JuiceMitApfelnDrin/CodinCodFrontend
          - name: backend
            path: backend/README.md
            target_repo: JuiceMitApfelnDrin/CodinCodBackend
          - name: types
            path: types/README.md
            target_repo: JuiceMitApfelnDrin/CodinCodTypes
          - name: codincod
            path: README.md
            target_repo: JuiceMitApfelnDrin/CodinCod

    steps:
    - name: Checkout the docs repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "juicemitapfelndrin@gmail.com"
        git config --global user.name "reeveng"

    - name: Sync README to the target repository
      run: |
        # Clone the target repository
        git clone https://github.com/${{ matrix.repo.target_repo }}.git
        cd $(basename "${{ matrix.repo.target_repo }}")

        # Copy the specific README from the docs repo
        cp ../${{ matrix.repo.path }} ./README.md

        # Commit and push the changes
        git add README.md
        git commit -m "docs: update README from docs repo"
        git push https://x-access-token:${{ secrets.ORG_PAT_TOKEN }}@github.com/${{ matrix.repo.target_repo }}.git
